# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

name: Docker Test

on:
  workflow_run:
    workflows:
      - "Publish to Azure Artifacts"
    types:
      - completed
    branches: [main, 'b-v*-patch*','feature-*']
  pull_request:
    branches: [main, 'b-v*-patch*','feature-*']
    paths:
      - "Docker/**/*"
  workflow_dispatch:

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CURRENT_STANDARD_VERSION: "5.2.0"
  PACKAGE_VERSION: "7.4"

jobs:
  cancel-if-required-workflows-did-not-succeed:
    if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion != 'success' }}
    runs-on: ubuntu-24.04
    steps:
      - run: throw "Cancelling because the required workflows did not succeed."
        shell: pwsh

  docker-lint:
    needs: cancel-if-required-workflows-did-not-succeed
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        image:
          - ods-api-bulk-load-console/alpine
          - ods-api-db-admin/alpine/pgsql
          - ods-api-db-ods-minimal/alpine/pgsql
          - ods-api-db-ods-sandbox/alpine/pgsql
          - ods-api-swaggerui/alpine
          - ods-api-web-api/alpine/mssql
          - ods-api-web-api/alpine/pgsql
          - ods-api-web-sandbox-admin/alpine/mssql
          - ods-api-web-sandbox-admin/alpine/pgsql
          - ods-api-db-admin/ubuntu/mssql
          - ods-api-db-ods-minimal/ubuntu/mssql
          - ods-api-db-ods-sandbox/ubuntu/mssql
    steps:
      - run: echo "success"

  FindStandardAndExtensionVersions:
    needs: cancel-if-required-workflows-did-not-succeed
    uses: Ed-Fi-Alliance-OSS/Ed-Fi-ODS/.github/workflows/Find Standard and Extension Versions.yml@874b608a0f3a14243e0035dd1222169fafcbe8d3
    with:
      calling_branch: ${{ github.head_ref || github.ref_name }}

  docker-build:
    needs: FindStandardAndExtensionVersions
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        StandardVersion: ${{ fromJson(needs.FindStandardAndExtensionVersions.outputs.StandardVersions) }}
        ExtensionVersion: ${{ fromJson(needs.FindStandardAndExtensionVersions.outputs.ExtensionVersions) }}
        dockerfile:
          [
            { name: "ods-api-bulk-load-console", path: "alpine" },
            { name: "ods-api-db-admin", path: "alpine/pgsql" },
            { name: "ods-api-db-ods-minimal", path: "alpine/pgsql" },
            { name: "ods-api-db-ods-sandbox", path: "alpine/pgsql" },
            { name: "ods-api-swaggerui", path: "alpine" },
            { name: "ods-api-web-api", path: "alpine/pgsql" },
            { name: "ods-api-web-api", path: "alpine/mssql" },
            { name: "ods-api-web-sandbox-admin", path: "alpine/pgsql" },
            { name: "ods-api-web-sandbox-admin", path: "alpine/mssql" },
            { name: "ods-api-db-admin", path: "ubuntu/mssql" },
            { name: "ods-api-db-ods-minimal", path: "ubuntu/mssql" },
            { name: "ods-api-db-ods-sandbox", path: "ubuntu/mssql" }
          ]        
    name: ${{ matrix.dockerfile.name }}/${{ matrix.dockerfile.path }} Image for (Standard ${{ matrix.StandardVersion }} Extension ${{ matrix.ExtensionVersion }})

    steps:
      - run: echo "success"
